export const FETCH_GH_TOKEN_REQUEST = 'FETCH_GH_TOKEN_REQUEST'
export const FETCH_GH_TOKEN_SUCCESS = 'FETCH_GH_TOKEN_SUCCESS'
export const FETCH_GH_TOKEN_ERROR = 'FETCH_GH_TOKEN_ERROR'
export const LOGOUT = 'LOGOUT'
