export const FETCH_GH_TOKEN_REQUEST = 'FETCH_GH_TOKEN_REQUEST'
export const FETCH_GH_TOKEN_SUCCESS = 'FETCH_GH_TOKEN_SUCCESS'
export const FETCH_GH_TOKEN_ERROR = 'FETCH_GH_TOKEN_ERROR'
export const LOGOUT = 'LOGOUT'

export const GIST_ADD = 'GIST_ADD'
export const GIST_DELETE = 'GIST_DELETE'
export const GIST_RENAME = 'GIST_RENAME'
export const NEW_GIST = 'NEW_GIST'
export const SET_ACTIVE_GIST = 'SET_ACTIVE_GIST'
export const CHANGE_GIST = 'CHANGE_GIST'
export const FETCH_GIST_FILE = 'FETCH_GIST_FILE'
export const FETCH_GIST_FILE_REQUEST = 'FETCH_GIST_FILE_REQUEST'
export const FETCH_GIST_FILE_SUCCESS = 'FETCH_GIST_FILE_SUCCESS'
export const FETCH_GIST_FILE_FAILURE = 'FETCH_GIST_FILE_FAILURE'

export const UPDATE_GIST = 'UPDATE_GIST'
export const UPDATE_GIST_SUCCESS = 'UPDATE_GIST_SUCCESS'
export const UPDATE_GIST_ERROR = 'UPDATE_GIST_ERROR'

export const UPDATE_GISTS_START = 'UPDATE_GISTS_START'
export const UPDATE_GISTS_FINISH = 'UPDATE_GISTS_FINISH'

export const FILE_ADD = 'FILE_ADD'
export const FILE_REMOVE = 'FILE_REMOVE'
export const FILE_RENAME = 'FILE_RENAME'

export const FILE_CONTENT_CHANGE = 'FILE_CONTENT_CHANGE'