export const FETCH_GH_TOKEN_REQUEST = 'FETCH_GH_TOKEN_REQUEST'
export const FETCH_GH_TOKEN_SUCCESS = 'FETCH_GH_TOKEN_SUCCESS'
export const FETCH_GH_TOKEN_ERROR = 'FETCH_GH_TOKEN_ERROR'
export const LOGOUT = 'LOGOUT'

export const CHANGE_GIST = 'CHANGE_GIST'

export const UPDATE_GIST = 'UPDATE_GIST'
export const UPDATE_GIST_SUCCESS = 'UPDATE_GIST_SUCCESS'
export const UPDATE_GIST_ERROR = 'UPDATE_GIST_ERROR'

export const UPDATE_GISTS_START = 'UPDATE_GISTS_START'
export const UPDATE_GISTS_FINISH = 'UPDATE_GISTS_FINISH'

export const FILE_ADD = 'FILE_ADD'
export const FILE_REMOVE = 'FILE_REMOVE'